language: node_js

sudo: false

node_js:
  - 'stable'
  - '8'
  - '6'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true

script: echo "Running tests against $(node -v)..."

jobs:
  include:
  - stage: Produce Coverage
    node_js: node
    script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

services:
  - mysql
